In [1]:
import pandas as pd

In [8]:
df = pd.read_excel("/content/MBU_Entry_Status_District_Wise 15-07-2026 12-10-17 PM.xlsx", sheet_name='MBU_Entry_Status_District_Wise')

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [9]:
df.columns = df.iloc[2].values

In [10]:
df = df.iloc[4:]

In [11]:
df = df[df['Academic Year'] == '2026-27']

In [53]:
df.head()

,District Name,District Code,Academic Year,Total Student,Total Students AADHAAR Provided,AADHAAR Verified-Passed(Yes),AADHAAR Verified-Failed(No),AADHAAR Verified-To be Done,MBU Pending (Age 5-15),MBU Pending (Age 15 and above),MBU Not Required,MBU Not Applicable,Status Check to be done
5,BALOD,2222,2026-27,124282,123608,115650,7573,385,4989,8032,102628,0,1
7,BALODABAZAR,2224,2026-27,215368,211289,201670,8873,746,10998,16286,174375,1,10
9,BALRAMPUR,2226,2026-27,152725,139275,124011,14309,955,1638,365,121984,1,23
11,BASTER,2215,2026-27,145538,136475,123715,11542,1218,2816,1155,119738,3,3
13,BEMETARA,2223,2026-27,158754,156635,152298,3945,392,7083,6239,138968,2,6

In [28]:
x = ((df['Status Check to be done'] + df['MBU Not Required']) / df['Total Student'])*100

In [36]:
df['MBU_done_%'] = x

In [37]:
df

,District Name,District Code,Academic Year,Total Student,Total Students AADHAAR Provided,AADHAAR Verified-Passed(Yes),AADHAAR Verified-Failed(No),AADHAAR Verified-To be Done,MBU Pending (Age 5-15),MBU Pending (Age 15 and above),MBU Not Required,MBU Not Applicable,Status Check to be done,MBU_done_%
5,BALOD,2222,2026-27,124282,123608,115650,7573,385,4989,8032,102628,0,1,82.577525
7,BALODABAZAR,2224,2026-27,215368,211289,201670,8873,746,10998,16286,174375,1,10,80.970711
9,BALRAMPUR,2226,2026-27,152725,139275,124011,14309,955,1638,365,121984,1,23,79.886725
11,BASTER,2215,2026-27,145538,136475,123715,11542,1218,2816,1155,119738,3,3,82.274732
13,BEMETARA,2223,2026-27,158754,156635,152298,3945,392,7083,6239,138968,2,6,87.540471
14,BIJAPUR,2220,2026-27,57176,41466,39400,1909,157,2820,2124,34448,3,5,60.2578
16,BILASPUR,2207,2026-27,344923,333277,304526,27106,1645,18460,16300,269736,1,29,78.210209
18,DANTEWADA,2216,2026-27,49385,46923,41197,4704,1022,1147,1249,38796,0,5,78.568391
20,DHAMTARI,2213,2026-27,123702,122923,118108,4472,343,1888,1466,114751,2,1,92.76487
22,DURG,2210,2026-27,272338,268884,258500,9464,920,4980,3597,249915,0,8,91.769419
24,GARIABAND,2225,2026-27,92014,89607,85179,4030,398,5263,1743,78170,0,3,84.957724
26,GOURELA PENDRA MARVAHI,2228,2026-27,52942,50771,47991,2647,133,909,718,46360,2,2,87.571304
27,JANJGIR - CHAMPA,2206,2026-27,200091,192505,180605,11353,547,6120,5214,169265,1,5,84.596509
28,JASHPUR,2203,2026-27,151528,146263,138877,6968,418,5860,8003,125006,3,5,82.500264
30,KANKER,2214,2026-27,121557,116702,107096,7993,1613,5943,7418,93727,3,5,77.109504
32,KAWARDHA,2208,2026-27,155815,150243,137317,12297,629,7180,5282,124844,3,8,80.128357
34,KHAIRAGARH-CHUIKHADAN-GANDAI,2230,2026-27,61893,60340,57206,2818,316,3631,1054,52520,0,1,84.857738
35,KONDAGAON,2217,2026-27,108110,101768,94683,6060,1025,4824,3227,86631,0,1,80.133198
37,KORBA,2205,2026-27,207583,202605,196155,5726,724,8086,5218,182845,1,5,88.085248
39,KORIYA,2201,2026-27,55774,54384,52221,2009,154,1752,1043,49414,8,4,88.604009
40,MAHASAMUND,2212,2026-27,187091,179640,162612,15995,1033,11623,11633,139350,1,5,74.485144
41,MANENDRAGARH-CHIRMIRI-BHARATPUR,2231,2026-27,61525,57497,54321,2883,293,1846,1222,51250,0,3,83.304348
43,MOHLA-MANPUR-CHOWKI,2232,2026-27,44413,42035,39566,2249,220,1230,1494,36841,0,1,82.953189
45,MUNGELI,2219,2026-27,139747,137041,131859,4578,604,4413,1589,125852,0,5,90.06061
47,NARAYANPUR,2218,2026-27,28003,23552,20521,2773,258,895,430,19193,0,3,68.549798
49,RAIGARH,2204,2026-27,178691,174502,168540,5525,437,11807,12848,143876,2,7,80.520563
51,RAIPUR,2211,2026-27,441459,432225,420623,10116,1486,24184,26089,370317,7,26,83.89069
53,RAJNANDGAON,2209,2026-27,153063,151295,146407,4274,614,3810,3078,139511,0,8,91.151356
55,SAKTI,2233,2026-27,117337,113725,106464,6973,288,5334,5571,95557,0,2,81.439785
57,SARANGARH-BILAIGARH,2229,2026-27,92749,91065,87390,3253,422,4321,2459,80609,0,1,86.911988
59,SUKMA,2221,2026-27,45893,41040,35712,5212,116,1402,874,33427,1,8,72.854248
61,SURAJPUR,2227,2026-27,137942,129108,122183,6354,571,10687,8617,102872,4,3,74.578446
62,SURGUJA,2202,2026-27,168033,163500,154125,8696,679,9943,12997,131166,2,17,78.069784

In [44]:
df['MBU_done_%'] = df['MBU_done_%'].astype('float').round(2)

In [46]:
df.to_csv("MBU_data.csv")